export { default as AboutMe } from './AboutMe'
export { default as Contact } from './Contact'
export { default as FavoriteWorks } from './FavoriteWorks'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Hero } from './Hero'
